/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: baidu.proto */

#ifndef PROTOBUF_C_baidu_2eproto__INCLUDED
#define PROTOBUF_C_baidu_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1000002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Baidu__BidRequest Baidu__BidRequest;
typedef struct _Baidu__BidRequest__Geo Baidu__BidRequest__Geo;
typedef struct _Baidu__BidRequest__Geo__Coordinate Baidu__BidRequest__Geo__Coordinate;
typedef struct _Baidu__BidRequest__Geo__UserLocation Baidu__BidRequest__Geo__UserLocation;
typedef struct _Baidu__BidRequest__Mobile Baidu__BidRequest__Mobile;
typedef struct _Baidu__BidRequest__Mobile__DeviceOsVersion Baidu__BidRequest__Mobile__DeviceOsVersion;
typedef struct _Baidu__BidRequest__Mobile__MobileApp Baidu__BidRequest__Mobile__MobileApp;
typedef struct _Baidu__BidRequest__AdSlot Baidu__BidRequest__AdSlot;
typedef struct _Baidu__BidResponse Baidu__BidResponse;
typedef struct _Baidu__BidResponse__Ad Baidu__BidResponse__Ad;


/* --- enums --- */

typedef enum _Baidu__BidRequest__Geo__Coordinate__Standard {
  BAIDU__BID_REQUEST__GEO__COORDINATE__STANDARD__BD_09 = 0,
  BAIDU__BID_REQUEST__GEO__COORDINATE__STANDARD__GCJ_02 = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__GEO__COORDINATE__STANDARD)
} Baidu__BidRequest__Geo__Coordinate__Standard;
typedef enum _Baidu__BidRequest__Mobile__MobileApp__AppInteractionType {
  BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__APP_INTERACTION_TYPE__TELEPHONE = 0,
  BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__APP_INTERACTION_TYPE__DOWNLOAD = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__APP_INTERACTION_TYPE)
} Baidu__BidRequest__Mobile__MobileApp__AppInteractionType;
typedef enum _Baidu__BidRequest__Mobile__MobileDeviceType {
  BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__UNKNOWN_DEVICE = 0,
  BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__HIGHEND_PHONE = 1,
  BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__TABLET = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE)
} Baidu__BidRequest__Mobile__MobileDeviceType;
typedef enum _Baidu__BidRequest__Mobile__OS {
  BAIDU__BID_REQUEST__MOBILE__OS__UNKNOWN_OS = 0,
  BAIDU__BID_REQUEST__MOBILE__OS__IOS = 1,
  BAIDU__BID_REQUEST__MOBILE__OS__ANDROID = 2,
  BAIDU__BID_REQUEST__MOBILE__OS__WINDOWS_PHONE = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__MOBILE__OS)
} Baidu__BidRequest__Mobile__OS;
typedef enum _Baidu__BidRequest__Mobile__WirelessNetworkType {
  BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__UNKNOWN_NETWORK = 0,
  BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__WIFI = 1,
  BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_2G = 2,
  BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_3G = 3,
  BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_4G = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE)
} Baidu__BidRequest__Mobile__WirelessNetworkType;
typedef enum _Baidu__BidRequest__Gender {
  BAIDU__BID_REQUEST__GENDER__UNKNOWN = 0,
  BAIDU__BID_REQUEST__GENDER__MALE = 1,
  BAIDU__BID_REQUEST__GENDER__FEMALE = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(BAIDU__BID_REQUEST__GENDER)
} Baidu__BidRequest__Gender;

/* --- messages --- */

struct  _Baidu__BidRequest__Geo__Coordinate
{
  ProtobufCMessage base;
  protobuf_c_boolean has_standard;
  Baidu__BidRequest__Geo__Coordinate__Standard standard;
  protobuf_c_boolean has_latitude;
  float latitude;
  protobuf_c_boolean has_longitude;
  float longitude;
};
#define BAIDU__BID_REQUEST__GEO__COORDINATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__geo__coordinate__descriptor) \
    , 0,0, 0,0, 0,0 }


struct  _Baidu__BidRequest__Geo__UserLocation
{
  ProtobufCMessage base;
  char *province;
  char *city;
  char *district;
  char *street;
};
#define BAIDU__BID_REQUEST__GEO__USER_LOCATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__geo__user_location__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Baidu__BidRequest__Geo
{
  ProtobufCMessage base;
  size_t n_user_coordinate;
  Baidu__BidRequest__Geo__Coordinate **user_coordinate;
  Baidu__BidRequest__Geo__UserLocation *user_location;
};
#define BAIDU__BID_REQUEST__GEO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__geo__descriptor) \
    , 0,NULL, NULL }


struct  _Baidu__BidRequest__Mobile__DeviceOsVersion
{
  ProtobufCMessage base;
  protobuf_c_boolean has_os_version_major;
  int32_t os_version_major;
  protobuf_c_boolean has_os_version_minor;
  int32_t os_version_minor;
  protobuf_c_boolean has_os_version_micro;
  int32_t os_version_micro;
};
#define BAIDU__BID_REQUEST__MOBILE__DEVICE_OS_VERSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__mobile__device_os_version__descriptor) \
    , 0,0, 0,0, 0,0 }


struct  _Baidu__BidRequest__Mobile__MobileApp
{
  ProtobufCMessage base;
  char *app_id;
  char *app_bundle_id;
  protobuf_c_boolean has_app_category;
  int32_t app_category;
  protobuf_c_boolean has_app_publisher_id;
  int32_t app_publisher_id;
  size_t n_app_interaction_type;
  Baidu__BidRequest__Mobile__MobileApp__AppInteractionType *app_interaction_type;
};
#define BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__mobile__mobile_app__descriptor) \
    , NULL, NULL, 0,0, 0,0, 0,NULL }


struct  _Baidu__BidRequest__Mobile
{
  ProtobufCMessage base;
  protobuf_c_boolean has_device_id;
  uint64_t device_id;
  protobuf_c_boolean has_device_type;
  Baidu__BidRequest__Mobile__MobileDeviceType device_type;
  protobuf_c_boolean has_platform;
  Baidu__BidRequest__Mobile__OS platform;
  Baidu__BidRequest__Mobile__DeviceOsVersion *os_version;
  char *brand;
  char *model;
  protobuf_c_boolean has_screen_width;
  int32_t screen_width;
  protobuf_c_boolean has_screen_height;
  int32_t screen_height;
  protobuf_c_boolean has_carrier_id;
  int64_t carrier_id;
  protobuf_c_boolean has_wireless_network_type;
  Baidu__BidRequest__Mobile__WirelessNetworkType wireless_network_type;
  char *for_advertising_id;
  Baidu__BidRequest__Mobile__MobileApp *mobile_app;
};
#define BAIDU__BID_REQUEST__MOBILE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__mobile__descriptor) \
    , 0,0, 0,0, 0,BAIDU__BID_REQUEST__MOBILE__OS__UNKNOWN_OS, NULL, NULL, NULL, 0,0, 0,0, 0,0, 0,0, NULL, NULL }


struct  _Baidu__BidRequest__AdSlot
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ad_block_key;
  int64_t ad_block_key;
  protobuf_c_boolean has_sequence_id;
  int32_t sequence_id;
  protobuf_c_boolean has_adslot_type;
  int32_t adslot_type;
  protobuf_c_boolean has_width;
  int32_t width;
  protobuf_c_boolean has_height;
  int32_t height;
  protobuf_c_boolean has_slot_visibility;
  int32_t slot_visibility;
  size_t n_creative_type;
  int32_t *creative_type;
  size_t n_excluded_landing_page_url;
  char **excluded_landing_page_url;
  protobuf_c_boolean has_minimum_cpm;
  int32_t minimum_cpm;
};
#define BAIDU__BID_REQUEST__AD_SLOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__ad_slot__descriptor) \
    , 0,0, 0,0, 0,0, 0,0, 0,0, 0,0, 0,NULL, 0,NULL, 0,0 }


struct  _Baidu__BidRequest
{
  ProtobufCMessage base;
  char *id;
  char *ip;
  char *user_agent;
  char *baidu_user_id;
  protobuf_c_boolean has_baidu_user_id_version;
  int32_t baidu_user_id_version;
  size_t n_user_category;
  int64_t *user_category;
  protobuf_c_boolean has_gender;
  Baidu__BidRequest__Gender gender;
  char *detected_language;
  char *flash_version;
  Baidu__BidRequest__Geo *user_geo_info;
  char *url;
  char *referer;
  protobuf_c_boolean has_site_category;
  int32_t site_category;
  protobuf_c_boolean has_site_quality;
  int32_t site_quality;
  protobuf_c_boolean has_page_type;
  int32_t page_type;
  size_t n_page_keyword;
  char **page_keyword;
  protobuf_c_boolean has_page_quality;
  int32_t page_quality;
  protobuf_c_boolean has_page_vertical;
  int32_t page_vertical;
  size_t n_excluded_product_category;
  int32_t *excluded_product_category;
  Baidu__BidRequest__Mobile *mobile;
  size_t n_adslot;
  Baidu__BidRequest__AdSlot **adslot;
  protobuf_c_boolean has_is_test;
  protobuf_c_boolean is_test;
  protobuf_c_boolean has_is_ping;
  protobuf_c_boolean is_ping;
};
#define BAIDU__BID_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_request__descriptor) \
    , NULL, NULL, NULL, NULL, 0,0, 0,NULL, 0,0, NULL, NULL, NULL, NULL, NULL, 0,0, 0,0, 0,0, 0,NULL, 0,0, 0,0, 0,NULL, NULL, 0,NULL, 0,0, 0,0 }


struct  _Baidu__BidResponse__Ad
{
  ProtobufCMessage base;
  protobuf_c_boolean has_sequence_id;
  int32_t sequence_id;
  protobuf_c_boolean has_creative_id;
  int64_t creative_id;
  protobuf_c_boolean has_max_cpm;
  int32_t max_cpm;
  char *extdata;
  protobuf_c_boolean has_is_cookie_matching;
  protobuf_c_boolean is_cookie_matching;
  char *html_snippet;
  protobuf_c_boolean has_advertiser_id;
  uint32_t advertiser_id;
  protobuf_c_boolean has_width;
  int32_t width;
  protobuf_c_boolean has_height;
  int32_t height;
  protobuf_c_boolean has_category;
  int32_t category;
  protobuf_c_boolean has_type;
  int32_t type;
  char *landing_page;
  size_t n_target_url;
  char **target_url;
};
#define BAIDU__BID_RESPONSE__AD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_response__ad__descriptor) \
    , 0,0, 0,0, 0,0, NULL, 0,0, NULL, 0,0, 0,0, 0,0, 0,0, 0,0, NULL, 0,NULL }


struct  _Baidu__BidResponse
{
  ProtobufCMessage base;
  char *id;
  size_t n_ad;
  Baidu__BidResponse__Ad **ad;
  char *debug_string;
  protobuf_c_boolean has_processing_time_ms;
  int32_t processing_time_ms;
};
#define BAIDU__BID_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&baidu__bid_response__descriptor) \
    , NULL, 0,NULL, NULL, 0,0 }


/* Baidu__BidRequest__Geo__Coordinate methods */
void   baidu__bid_request__geo__coordinate__init
                     (Baidu__BidRequest__Geo__Coordinate         *message);
/* Baidu__BidRequest__Geo__UserLocation methods */
void   baidu__bid_request__geo__user_location__init
                     (Baidu__BidRequest__Geo__UserLocation         *message);
/* Baidu__BidRequest__Geo methods */
void   baidu__bid_request__geo__init
                     (Baidu__BidRequest__Geo         *message);
/* Baidu__BidRequest__Mobile__DeviceOsVersion methods */
void   baidu__bid_request__mobile__device_os_version__init
                     (Baidu__BidRequest__Mobile__DeviceOsVersion         *message);
/* Baidu__BidRequest__Mobile__MobileApp methods */
void   baidu__bid_request__mobile__mobile_app__init
                     (Baidu__BidRequest__Mobile__MobileApp         *message);
/* Baidu__BidRequest__Mobile methods */
void   baidu__bid_request__mobile__init
                     (Baidu__BidRequest__Mobile         *message);
/* Baidu__BidRequest__AdSlot methods */
void   baidu__bid_request__ad_slot__init
                     (Baidu__BidRequest__AdSlot         *message);
/* Baidu__BidRequest methods */
void   baidu__bid_request__init
                     (Baidu__BidRequest         *message);
size_t baidu__bid_request__get_packed_size
                     (const Baidu__BidRequest   *message);
size_t baidu__bid_request__pack
                     (const Baidu__BidRequest   *message,
                      uint8_t             *out);
size_t baidu__bid_request__pack_to_buffer
                     (const Baidu__BidRequest   *message,
                      ProtobufCBuffer     *buffer);
Baidu__BidRequest *
       baidu__bid_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   baidu__bid_request__free_unpacked
                     (Baidu__BidRequest *message,
                      ProtobufCAllocator *allocator);
/* Baidu__BidResponse__Ad methods */
void   baidu__bid_response__ad__init
                     (Baidu__BidResponse__Ad         *message);
/* Baidu__BidResponse methods */
void   baidu__bid_response__init
                     (Baidu__BidResponse         *message);
size_t baidu__bid_response__get_packed_size
                     (const Baidu__BidResponse   *message);
size_t baidu__bid_response__pack
                     (const Baidu__BidResponse   *message,
                      uint8_t             *out);
size_t baidu__bid_response__pack_to_buffer
                     (const Baidu__BidResponse   *message,
                      ProtobufCBuffer     *buffer);
Baidu__BidResponse *
       baidu__bid_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   baidu__bid_response__free_unpacked
                     (Baidu__BidResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Baidu__BidRequest__Geo__Coordinate_Closure)
                 (const Baidu__BidRequest__Geo__Coordinate *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__Geo__UserLocation_Closure)
                 (const Baidu__BidRequest__Geo__UserLocation *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__Geo_Closure)
                 (const Baidu__BidRequest__Geo *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__Mobile__DeviceOsVersion_Closure)
                 (const Baidu__BidRequest__Mobile__DeviceOsVersion *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__Mobile__MobileApp_Closure)
                 (const Baidu__BidRequest__Mobile__MobileApp *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__Mobile_Closure)
                 (const Baidu__BidRequest__Mobile *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest__AdSlot_Closure)
                 (const Baidu__BidRequest__AdSlot *message,
                  void *closure_data);
typedef void (*Baidu__BidRequest_Closure)
                 (const Baidu__BidRequest *message,
                  void *closure_data);
typedef void (*Baidu__BidResponse__Ad_Closure)
                 (const Baidu__BidResponse__Ad *message,
                  void *closure_data);
typedef void (*Baidu__BidResponse_Closure)
                 (const Baidu__BidResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor baidu__bid_request__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__geo__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__geo__coordinate__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__geo__coordinate__standard__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__geo__user_location__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__mobile__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__mobile__device_os_version__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__mobile__mobile_app__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__mobile__mobile_app__app_interaction_type__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__mobile__mobile_device_type__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__mobile__os__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__mobile__wireless_network_type__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_request__ad_slot__descriptor;
extern const ProtobufCEnumDescriptor    baidu__bid_request__gender__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_response__descriptor;
extern const ProtobufCMessageDescriptor baidu__bid_response__ad__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_baidu_2eproto__INCLUDED */
