/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: baidu.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "baidu.pb-c.h"
void   baidu__bid_request__geo__coordinate__init
                     (Baidu__BidRequest__Geo__Coordinate         *message)
{
  static Baidu__BidRequest__Geo__Coordinate init_value = BAIDU__BID_REQUEST__GEO__COORDINATE__INIT;
  *message = init_value;
}
void   baidu__bid_request__geo__user_location__init
                     (Baidu__BidRequest__Geo__UserLocation         *message)
{
  static Baidu__BidRequest__Geo__UserLocation init_value = BAIDU__BID_REQUEST__GEO__USER_LOCATION__INIT;
  *message = init_value;
}
void   baidu__bid_request__geo__init
                     (Baidu__BidRequest__Geo         *message)
{
  static Baidu__BidRequest__Geo init_value = BAIDU__BID_REQUEST__GEO__INIT;
  *message = init_value;
}
void   baidu__bid_request__mobile__device_os_version__init
                     (Baidu__BidRequest__Mobile__DeviceOsVersion         *message)
{
  static Baidu__BidRequest__Mobile__DeviceOsVersion init_value = BAIDU__BID_REQUEST__MOBILE__DEVICE_OS_VERSION__INIT;
  *message = init_value;
}
void   baidu__bid_request__mobile__mobile_app__init
                     (Baidu__BidRequest__Mobile__MobileApp         *message)
{
  static Baidu__BidRequest__Mobile__MobileApp init_value = BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__INIT;
  *message = init_value;
}
void   baidu__bid_request__mobile__init
                     (Baidu__BidRequest__Mobile         *message)
{
  static Baidu__BidRequest__Mobile init_value = BAIDU__BID_REQUEST__MOBILE__INIT;
  *message = init_value;
}
void   baidu__bid_request__ad_slot__init
                     (Baidu__BidRequest__AdSlot         *message)
{
  static Baidu__BidRequest__AdSlot init_value = BAIDU__BID_REQUEST__AD_SLOT__INIT;
  *message = init_value;
}
void   baidu__bid_request__init
                     (Baidu__BidRequest         *message)
{
  static Baidu__BidRequest init_value = BAIDU__BID_REQUEST__INIT;
  *message = init_value;
}
size_t baidu__bid_request__get_packed_size
                     (const Baidu__BidRequest *message)
{
  assert(message->base.descriptor == &baidu__bid_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t baidu__bid_request__pack
                     (const Baidu__BidRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &baidu__bid_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t baidu__bid_request__pack_to_buffer
                     (const Baidu__BidRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &baidu__bid_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Baidu__BidRequest *
       baidu__bid_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Baidu__BidRequest *)
     protobuf_c_message_unpack (&baidu__bid_request__descriptor,
                                allocator, len, data);
}
void   baidu__bid_request__free_unpacked
                     (Baidu__BidRequest *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &baidu__bid_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   baidu__bid_response__ad__init
                     (Baidu__BidResponse__Ad         *message)
{
  static Baidu__BidResponse__Ad init_value = BAIDU__BID_RESPONSE__AD__INIT;
  *message = init_value;
}
void   baidu__bid_response__init
                     (Baidu__BidResponse         *message)
{
  static Baidu__BidResponse init_value = BAIDU__BID_RESPONSE__INIT;
  *message = init_value;
}
size_t baidu__bid_response__get_packed_size
                     (const Baidu__BidResponse *message)
{
  assert(message->base.descriptor == &baidu__bid_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t baidu__bid_response__pack
                     (const Baidu__BidResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &baidu__bid_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t baidu__bid_response__pack_to_buffer
                     (const Baidu__BidResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &baidu__bid_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Baidu__BidResponse *
       baidu__bid_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Baidu__BidResponse *)
     protobuf_c_message_unpack (&baidu__bid_response__descriptor,
                                allocator, len, data);
}
void   baidu__bid_response__free_unpacked
                     (Baidu__BidResponse *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &baidu__bid_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue baidu__bid_request__geo__coordinate__standard__enum_values_by_number[2] =
{
  { "BD_09", "BAIDU__BID_REQUEST__GEO__COORDINATE__STANDARD__BD_09", 0 },
  { "GCJ_02", "BAIDU__BID_REQUEST__GEO__COORDINATE__STANDARD__GCJ_02", 1 },
};
static const ProtobufCIntRange baidu__bid_request__geo__coordinate__standard__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex baidu__bid_request__geo__coordinate__standard__enum_values_by_name[2] =
{
  { "BD_09", 0 },
  { "GCJ_02", 1 },
};
const ProtobufCEnumDescriptor baidu__bid_request__geo__coordinate__standard__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Geo.Coordinate.Standard",
  "Standard",
  "Baidu__BidRequest__Geo__Coordinate__Standard",
  "Baidu",
  2,
  baidu__bid_request__geo__coordinate__standard__enum_values_by_number,
  2,
  baidu__bid_request__geo__coordinate__standard__enum_values_by_name,
  1,
  baidu__bid_request__geo__coordinate__standard__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__geo__coordinate__field_descriptors[3] =
{
  {
    "standard",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest__Geo__Coordinate, has_standard),
    offsetof(Baidu__BidRequest__Geo__Coordinate, standard),
    &baidu__bid_request__geo__coordinate__standard__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Baidu__BidRequest__Geo__Coordinate, has_latitude),
    offsetof(Baidu__BidRequest__Geo__Coordinate, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "longitude",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Baidu__BidRequest__Geo__Coordinate, has_longitude),
    offsetof(Baidu__BidRequest__Geo__Coordinate, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__geo__coordinate__field_indices_by_name[] = {
  1,   /* field[1] = latitude */
  2,   /* field[2] = longitude */
  0,   /* field[0] = standard */
};
static const ProtobufCIntRange baidu__bid_request__geo__coordinate__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor baidu__bid_request__geo__coordinate__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Geo.Coordinate",
  "Coordinate",
  "Baidu__BidRequest__Geo__Coordinate",
  "Baidu",
  sizeof(Baidu__BidRequest__Geo__Coordinate),
  3,
  baidu__bid_request__geo__coordinate__field_descriptors,
  baidu__bid_request__geo__coordinate__field_indices_by_name,
  1,  baidu__bid_request__geo__coordinate__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__geo__coordinate__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__geo__user_location__field_descriptors[4] =
{
  {
    "province",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Geo__UserLocation, province),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "city",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Geo__UserLocation, city),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "district",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Geo__UserLocation, district),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "street",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Geo__UserLocation, street),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__geo__user_location__field_indices_by_name[] = {
  1,   /* field[1] = city */
  2,   /* field[2] = district */
  0,   /* field[0] = province */
  3,   /* field[3] = street */
};
static const ProtobufCIntRange baidu__bid_request__geo__user_location__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor baidu__bid_request__geo__user_location__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Geo.UserLocation",
  "UserLocation",
  "Baidu__BidRequest__Geo__UserLocation",
  "Baidu",
  sizeof(Baidu__BidRequest__Geo__UserLocation),
  4,
  baidu__bid_request__geo__user_location__field_descriptors,
  baidu__bid_request__geo__user_location__field_indices_by_name,
  1,  baidu__bid_request__geo__user_location__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__geo__user_location__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__geo__field_descriptors[2] =
{
  {
    "user_coordinate",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Baidu__BidRequest__Geo, n_user_coordinate),
    offsetof(Baidu__BidRequest__Geo, user_coordinate),
    &baidu__bid_request__geo__coordinate__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_location",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Geo, user_location),
    &baidu__bid_request__geo__user_location__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__geo__field_indices_by_name[] = {
  0,   /* field[0] = user_coordinate */
  1,   /* field[1] = user_location */
};
static const ProtobufCIntRange baidu__bid_request__geo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor baidu__bid_request__geo__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Geo",
  "Geo",
  "Baidu__BidRequest__Geo",
  "Baidu",
  sizeof(Baidu__BidRequest__Geo),
  2,
  baidu__bid_request__geo__field_descriptors,
  baidu__bid_request__geo__field_indices_by_name,
  1,  baidu__bid_request__geo__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__geo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__mobile__device_os_version__field_descriptors[3] =
{
  {
    "os_version_major",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, has_os_version_major),
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, os_version_major),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os_version_minor",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, has_os_version_minor),
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, os_version_minor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os_version_micro",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, has_os_version_micro),
    offsetof(Baidu__BidRequest__Mobile__DeviceOsVersion, os_version_micro),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__mobile__device_os_version__field_indices_by_name[] = {
  0,   /* field[0] = os_version_major */
  2,   /* field[2] = os_version_micro */
  1,   /* field[1] = os_version_minor */
};
static const ProtobufCIntRange baidu__bid_request__mobile__device_os_version__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor baidu__bid_request__mobile__device_os_version__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.DeviceOsVersion",
  "DeviceOsVersion",
  "Baidu__BidRequest__Mobile__DeviceOsVersion",
  "Baidu",
  sizeof(Baidu__BidRequest__Mobile__DeviceOsVersion),
  3,
  baidu__bid_request__mobile__device_os_version__field_descriptors,
  baidu__bid_request__mobile__device_os_version__field_indices_by_name,
  1,  baidu__bid_request__mobile__device_os_version__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__mobile__device_os_version__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue baidu__bid_request__mobile__mobile_app__app_interaction_type__enum_values_by_number[2] =
{
  { "TELEPHONE", "BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__APP_INTERACTION_TYPE__TELEPHONE", 0 },
  { "DOWNLOAD", "BAIDU__BID_REQUEST__MOBILE__MOBILE_APP__APP_INTERACTION_TYPE__DOWNLOAD", 1 },
};
static const ProtobufCIntRange baidu__bid_request__mobile__mobile_app__app_interaction_type__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex baidu__bid_request__mobile__mobile_app__app_interaction_type__enum_values_by_name[2] =
{
  { "DOWNLOAD", 1 },
  { "TELEPHONE", 0 },
};
const ProtobufCEnumDescriptor baidu__bid_request__mobile__mobile_app__app_interaction_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.MobileApp.AppInteractionType",
  "AppInteractionType",
  "Baidu__BidRequest__Mobile__MobileApp__AppInteractionType",
  "Baidu",
  2,
  baidu__bid_request__mobile__mobile_app__app_interaction_type__enum_values_by_number,
  2,
  baidu__bid_request__mobile__mobile_app__app_interaction_type__enum_values_by_name,
  1,
  baidu__bid_request__mobile__mobile_app__app_interaction_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__mobile__mobile_app__field_descriptors[5] =
{
  {
    "app_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile__MobileApp, app_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_bundle_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile__MobileApp, app_bundle_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_category",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile__MobileApp, has_app_category),
    offsetof(Baidu__BidRequest__Mobile__MobileApp, app_category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_publisher_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile__MobileApp, has_app_publisher_id),
    offsetof(Baidu__BidRequest__Mobile__MobileApp, app_publisher_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app_interaction_type",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest__Mobile__MobileApp, n_app_interaction_type),
    offsetof(Baidu__BidRequest__Mobile__MobileApp, app_interaction_type),
    &baidu__bid_request__mobile__mobile_app__app_interaction_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__mobile__mobile_app__field_indices_by_name[] = {
  1,   /* field[1] = app_bundle_id */
  2,   /* field[2] = app_category */
  0,   /* field[0] = app_id */
  4,   /* field[4] = app_interaction_type */
  3,   /* field[3] = app_publisher_id */
};
static const ProtobufCIntRange baidu__bid_request__mobile__mobile_app__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor baidu__bid_request__mobile__mobile_app__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.MobileApp",
  "MobileApp",
  "Baidu__BidRequest__Mobile__MobileApp",
  "Baidu",
  sizeof(Baidu__BidRequest__Mobile__MobileApp),
  5,
  baidu__bid_request__mobile__mobile_app__field_descriptors,
  baidu__bid_request__mobile__mobile_app__field_indices_by_name,
  1,  baidu__bid_request__mobile__mobile_app__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__mobile__mobile_app__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue baidu__bid_request__mobile__mobile_device_type__enum_values_by_number[3] =
{
  { "UNKNOWN_DEVICE", "BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__UNKNOWN_DEVICE", 0 },
  { "HIGHEND_PHONE", "BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__HIGHEND_PHONE", 1 },
  { "TABLET", "BAIDU__BID_REQUEST__MOBILE__MOBILE_DEVICE_TYPE__TABLET", 2 },
};
static const ProtobufCIntRange baidu__bid_request__mobile__mobile_device_type__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex baidu__bid_request__mobile__mobile_device_type__enum_values_by_name[3] =
{
  { "HIGHEND_PHONE", 1 },
  { "TABLET", 2 },
  { "UNKNOWN_DEVICE", 0 },
};
const ProtobufCEnumDescriptor baidu__bid_request__mobile__mobile_device_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.MobileDeviceType",
  "MobileDeviceType",
  "Baidu__BidRequest__Mobile__MobileDeviceType",
  "Baidu",
  3,
  baidu__bid_request__mobile__mobile_device_type__enum_values_by_number,
  3,
  baidu__bid_request__mobile__mobile_device_type__enum_values_by_name,
  1,
  baidu__bid_request__mobile__mobile_device_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue baidu__bid_request__mobile__os__enum_values_by_number[4] =
{
  { "UNKNOWN_OS", "BAIDU__BID_REQUEST__MOBILE__OS__UNKNOWN_OS", 0 },
  { "IOS", "BAIDU__BID_REQUEST__MOBILE__OS__IOS", 1 },
  { "ANDROID", "BAIDU__BID_REQUEST__MOBILE__OS__ANDROID", 2 },
  { "WINDOWS_PHONE", "BAIDU__BID_REQUEST__MOBILE__OS__WINDOWS_PHONE", 3 },
};
static const ProtobufCIntRange baidu__bid_request__mobile__os__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex baidu__bid_request__mobile__os__enum_values_by_name[4] =
{
  { "ANDROID", 2 },
  { "IOS", 1 },
  { "UNKNOWN_OS", 0 },
  { "WINDOWS_PHONE", 3 },
};
const ProtobufCEnumDescriptor baidu__bid_request__mobile__os__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.OS",
  "OS",
  "Baidu__BidRequest__Mobile__OS",
  "Baidu",
  4,
  baidu__bid_request__mobile__os__enum_values_by_number,
  4,
  baidu__bid_request__mobile__os__enum_values_by_name,
  1,
  baidu__bid_request__mobile__os__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue baidu__bid_request__mobile__wireless_network_type__enum_values_by_number[5] =
{
  { "UNKNOWN_NETWORK", "BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__UNKNOWN_NETWORK", 0 },
  { "WIFI", "BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__WIFI", 1 },
  { "MOBILE_2G", "BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_2G", 2 },
  { "MOBILE_3G", "BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_3G", 3 },
  { "MOBILE_4G", "BAIDU__BID_REQUEST__MOBILE__WIRELESS_NETWORK_TYPE__MOBILE_4G", 4 },
};
static const ProtobufCIntRange baidu__bid_request__mobile__wireless_network_type__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex baidu__bid_request__mobile__wireless_network_type__enum_values_by_name[5] =
{
  { "MOBILE_2G", 2 },
  { "MOBILE_3G", 3 },
  { "MOBILE_4G", 4 },
  { "UNKNOWN_NETWORK", 0 },
  { "WIFI", 1 },
};
const ProtobufCEnumDescriptor baidu__bid_request__mobile__wireless_network_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile.WirelessNetworkType",
  "WirelessNetworkType",
  "Baidu__BidRequest__Mobile__WirelessNetworkType",
  "Baidu",
  5,
  baidu__bid_request__mobile__wireless_network_type__enum_values_by_number,
  5,
  baidu__bid_request__mobile__wireless_network_type__enum_values_by_name,
  1,
  baidu__bid_request__mobile__wireless_network_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Baidu__BidRequest__Mobile__OS baidu__bid_request__mobile__platform__default_value = BAIDU__BID_REQUEST__MOBILE__OS__UNKNOWN_OS;
static const ProtobufCFieldDescriptor baidu__bid_request__mobile__field_descriptors[12] =
{
  {
    "device_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Baidu__BidRequest__Mobile, has_device_id),
    offsetof(Baidu__BidRequest__Mobile, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest__Mobile, has_device_type),
    offsetof(Baidu__BidRequest__Mobile, device_type),
    &baidu__bid_request__mobile__mobile_device_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "platform",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest__Mobile, has_platform),
    offsetof(Baidu__BidRequest__Mobile, platform),
    &baidu__bid_request__mobile__os__descriptor,
    &baidu__bid_request__mobile__platform__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "os_version",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile, os_version),
    &baidu__bid_request__mobile__device_os_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brand",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile, brand),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile, model),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_width",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile, has_screen_width),
    offsetof(Baidu__BidRequest__Mobile, screen_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "screen_height",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__Mobile, has_screen_height),
    offsetof(Baidu__BidRequest__Mobile, screen_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "carrier_id",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Baidu__BidRequest__Mobile, has_carrier_id),
    offsetof(Baidu__BidRequest__Mobile, carrier_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wireless_network_type",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest__Mobile, has_wireless_network_type),
    offsetof(Baidu__BidRequest__Mobile, wireless_network_type),
    &baidu__bid_request__mobile__wireless_network_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "for_advertising_id",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile, for_advertising_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mobile_app",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest__Mobile, mobile_app),
    &baidu__bid_request__mobile__mobile_app__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__mobile__field_indices_by_name[] = {
  4,   /* field[4] = brand */
  8,   /* field[8] = carrier_id */
  0,   /* field[0] = device_id */
  1,   /* field[1] = device_type */
  10,   /* field[10] = for_advertising_id */
  11,   /* field[11] = mobile_app */
  5,   /* field[5] = model */
  3,   /* field[3] = os_version */
  2,   /* field[2] = platform */
  7,   /* field[7] = screen_height */
  6,   /* field[6] = screen_width */
  9,   /* field[9] = wireless_network_type */
};
static const ProtobufCIntRange baidu__bid_request__mobile__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor baidu__bid_request__mobile__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Mobile",
  "Mobile",
  "Baidu__BidRequest__Mobile",
  "Baidu",
  sizeof(Baidu__BidRequest__Mobile),
  12,
  baidu__bid_request__mobile__field_descriptors,
  baidu__bid_request__mobile__field_indices_by_name,
  1,  baidu__bid_request__mobile__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__mobile__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_request__ad_slot__field_descriptors[9] =
{
  {
    "ad_block_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Baidu__BidRequest__AdSlot, has_ad_block_key),
    offsetof(Baidu__BidRequest__AdSlot, ad_block_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sequence_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_sequence_id),
    offsetof(Baidu__BidRequest__AdSlot, sequence_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adslot_type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_adslot_type),
    offsetof(Baidu__BidRequest__AdSlot, adslot_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_width),
    offsetof(Baidu__BidRequest__AdSlot, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_height),
    offsetof(Baidu__BidRequest__AdSlot, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_visibility",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_slot_visibility),
    offsetof(Baidu__BidRequest__AdSlot, slot_visibility),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creative_type",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, n_creative_type),
    offsetof(Baidu__BidRequest__AdSlot, creative_type),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "excluded_landing_page_url",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Baidu__BidRequest__AdSlot, n_excluded_landing_page_url),
    offsetof(Baidu__BidRequest__AdSlot, excluded_landing_page_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minimum_cpm",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest__AdSlot, has_minimum_cpm),
    offsetof(Baidu__BidRequest__AdSlot, minimum_cpm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__ad_slot__field_indices_by_name[] = {
  0,   /* field[0] = ad_block_key */
  2,   /* field[2] = adslot_type */
  6,   /* field[6] = creative_type */
  7,   /* field[7] = excluded_landing_page_url */
  4,   /* field[4] = height */
  8,   /* field[8] = minimum_cpm */
  1,   /* field[1] = sequence_id */
  5,   /* field[5] = slot_visibility */
  3,   /* field[3] = width */
};
static const ProtobufCIntRange baidu__bid_request__ad_slot__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor baidu__bid_request__ad_slot__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.AdSlot",
  "AdSlot",
  "Baidu__BidRequest__AdSlot",
  "Baidu",
  sizeof(Baidu__BidRequest__AdSlot),
  9,
  baidu__bid_request__ad_slot__field_descriptors,
  baidu__bid_request__ad_slot__field_indices_by_name,
  1,  baidu__bid_request__ad_slot__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__ad_slot__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue baidu__bid_request__gender__enum_values_by_number[3] =
{
  { "UNKNOWN", "BAIDU__BID_REQUEST__GENDER__UNKNOWN", 0 },
  { "MALE", "BAIDU__BID_REQUEST__GENDER__MALE", 1 },
  { "FEMALE", "BAIDU__BID_REQUEST__GENDER__FEMALE", 2 },
};
static const ProtobufCIntRange baidu__bid_request__gender__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex baidu__bid_request__gender__enum_values_by_name[3] =
{
  { "FEMALE", 2 },
  { "MALE", 1 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor baidu__bid_request__gender__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest.Gender",
  "Gender",
  "Baidu__BidRequest__Gender",
  "Baidu",
  3,
  baidu__bid_request__gender__enum_values_by_number,
  3,
  baidu__bid_request__gender__enum_values_by_name,
  1,
  baidu__bid_request__gender__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const protobuf_c_boolean baidu__bid_request__is_test__default_value = 0;
static const protobuf_c_boolean baidu__bid_request__is_ping__default_value = 0;
static const ProtobufCFieldDescriptor baidu__bid_request__field_descriptors[23] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_agent",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, user_agent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baidu_user_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, baidu_user_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baidu_user_id_version",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_baidu_user_id_version),
    offsetof(Baidu__BidRequest, baidu_user_id_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_category",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Baidu__BidRequest, n_user_category),
    offsetof(Baidu__BidRequest, user_category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Baidu__BidRequest, has_gender),
    offsetof(Baidu__BidRequest, gender),
    &baidu__bid_request__gender__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "detected_language",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, detected_language),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flash_version",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, flash_version),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "referer",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, referer),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "site_category",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_site_category),
    offsetof(Baidu__BidRequest, site_category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "site_quality",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_site_quality),
    offsetof(Baidu__BidRequest, site_quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_type",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_page_type),
    offsetof(Baidu__BidRequest, page_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_keyword",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Baidu__BidRequest, n_page_keyword),
    offsetof(Baidu__BidRequest, page_keyword),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_quality",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_page_quality),
    offsetof(Baidu__BidRequest, page_quality),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "excluded_product_category",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, n_excluded_product_category),
    offsetof(Baidu__BidRequest, excluded_product_category),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adslot",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Baidu__BidRequest, n_adslot),
    offsetof(Baidu__BidRequest, adslot),
    &baidu__bid_request__ad_slot__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "page_vertical",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidRequest, has_page_vertical),
    offsetof(Baidu__BidRequest, page_vertical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_test",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Baidu__BidRequest, has_is_test),
    offsetof(Baidu__BidRequest, is_test),
    NULL,
    &baidu__bid_request__is_test__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_ping",
    27,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Baidu__BidRequest, has_is_ping),
    offsetof(Baidu__BidRequest, is_ping),
    NULL,
    &baidu__bid_request__is_ping__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_geo_info",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, user_geo_info),
    &baidu__bid_request__geo__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mobile",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidRequest, mobile),
    &baidu__bid_request__mobile__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_request__field_indices_by_name[] = {
  17,   /* field[17] = adslot */
  3,   /* field[3] = baidu_user_id */
  4,   /* field[4] = baidu_user_id_version */
  7,   /* field[7] = detected_language */
  16,   /* field[16] = excluded_product_category */
  8,   /* field[8] = flash_version */
  6,   /* field[6] = gender */
  0,   /* field[0] = id */
  1,   /* field[1] = ip */
  20,   /* field[20] = is_ping */
  19,   /* field[19] = is_test */
  22,   /* field[22] = mobile */
  14,   /* field[14] = page_keyword */
  15,   /* field[15] = page_quality */
  13,   /* field[13] = page_type */
  18,   /* field[18] = page_vertical */
  10,   /* field[10] = referer */
  11,   /* field[11] = site_category */
  12,   /* field[12] = site_quality */
  9,   /* field[9] = url */
  2,   /* field[2] = user_agent */
  5,   /* field[5] = user_category */
  21,   /* field[21] = user_geo_info */
};
static const ProtobufCIntRange baidu__bid_request__number_ranges[4 + 1] =
{
  { 1, 0 },
  { 9, 7 },
  { 17, 14 },
  { 26, 19 },
  { 0, 23 }
};
const ProtobufCMessageDescriptor baidu__bid_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidRequest",
  "BidRequest",
  "Baidu__BidRequest",
  "Baidu",
  sizeof(Baidu__BidRequest),
  23,
  baidu__bid_request__field_descriptors,
  baidu__bid_request__field_indices_by_name,
  4,  baidu__bid_request__number_ranges,
  (ProtobufCMessageInit) baidu__bid_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_response__ad__field_descriptors[13] =
{
  {
    "sequence_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_sequence_id),
    offsetof(Baidu__BidResponse__Ad, sequence_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creative_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Baidu__BidResponse__Ad, has_creative_id),
    offsetof(Baidu__BidResponse__Ad, creative_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_cpm",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_max_cpm),
    offsetof(Baidu__BidResponse__Ad, max_cpm),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extdata",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidResponse__Ad, extdata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_cookie_matching",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Baidu__BidResponse__Ad, has_is_cookie_matching),
    offsetof(Baidu__BidResponse__Ad, is_cookie_matching),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "html_snippet",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidResponse__Ad, html_snippet),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "advertiser_id",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Baidu__BidResponse__Ad, has_advertiser_id),
    offsetof(Baidu__BidResponse__Ad, advertiser_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_width),
    offsetof(Baidu__BidResponse__Ad, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_height),
    offsetof(Baidu__BidResponse__Ad, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_category),
    offsetof(Baidu__BidResponse__Ad, category),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse__Ad, has_type),
    offsetof(Baidu__BidResponse__Ad, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "landing_page",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidResponse__Ad, landing_page),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_url",
    14,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Baidu__BidResponse__Ad, n_target_url),
    offsetof(Baidu__BidResponse__Ad, target_url),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_response__ad__field_indices_by_name[] = {
  6,   /* field[6] = advertiser_id */
  9,   /* field[9] = category */
  1,   /* field[1] = creative_id */
  3,   /* field[3] = extdata */
  8,   /* field[8] = height */
  5,   /* field[5] = html_snippet */
  4,   /* field[4] = is_cookie_matching */
  11,   /* field[11] = landing_page */
  2,   /* field[2] = max_cpm */
  0,   /* field[0] = sequence_id */
  12,   /* field[12] = target_url */
  10,   /* field[10] = type */
  7,   /* field[7] = width */
};
static const ProtobufCIntRange baidu__bid_response__ad__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor baidu__bid_response__ad__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidResponse.Ad",
  "Ad",
  "Baidu__BidResponse__Ad",
  "Baidu",
  sizeof(Baidu__BidResponse__Ad),
  13,
  baidu__bid_response__ad__field_descriptors,
  baidu__bid_response__ad__field_indices_by_name,
  2,  baidu__bid_response__ad__number_ranges,
  (ProtobufCMessageInit) baidu__bid_response__ad__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor baidu__bid_response__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ad",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Baidu__BidResponse, n_ad),
    offsetof(Baidu__BidResponse, ad),
    &baidu__bid_response__ad__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "debug_string",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Baidu__BidResponse, debug_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "processing_time_ms",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Baidu__BidResponse, has_processing_time_ms),
    offsetof(Baidu__BidResponse, processing_time_ms),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned baidu__bid_response__field_indices_by_name[] = {
  1,   /* field[1] = ad */
  2,   /* field[2] = debug_string */
  0,   /* field[0] = id */
  3,   /* field[3] = processing_time_ms */
};
static const ProtobufCIntRange baidu__bid_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor baidu__bid_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Baidu.BidResponse",
  "BidResponse",
  "Baidu__BidResponse",
  "Baidu",
  sizeof(Baidu__BidResponse),
  4,
  baidu__bid_response__field_descriptors,
  baidu__bid_response__field_indices_by_name,
  1,  baidu__bid_response__number_ranges,
  (ProtobufCMessageInit) baidu__bid_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
